// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function GetProjects() {
    return window['go']['main']['App']['GetProjects']();
}

export function CreateProject(arg1, arg2) {
    return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1) {
    return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ActivateProject(arg1) {
    return window['go']['main']['App']['ActivateProject'](arg1);
}

export function GetShards(arg1) {
    return window['go']['main']['App']['GetShards'](arg1);
} 

export function CreateShard(arg1) {
    return window['go']['main']['App']['CreateShard'](arg1);
}

export function GetWailsConfig() {
    return window['go']['main']['App']['GetWailsConfig']();
}
