// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {main} from '../models';

export function ActivateProject(arg1:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<repository.Project>;

export function CreateShard(arg1:string):Promise<repository.Shard>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProjects():Promise<Array<repository.Project>>;

export function GetShards(arg1:string):Promise<Array<repository.Shard>>;

export function GetWailsConfig():Promise<main.WailsConfig>;

export function Greet(arg1:string):Promise<string>;
