// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProject(arg1) {
  return window['go']['main']['App']['ActivateProject'](arg1);
}

export function ActivateShard(arg1) {
  return window['go']['main']['App']['ActivateShard'](arg1);
}

export function ApplyDDL(arg1, arg2) {
  return window['go']['main']['App']['ApplyDDL'](arg1, arg2);
}

export function CommitSchemaDraft(arg1, arg2) {
  return window['go']['main']['App']['CommitSchemaDraft'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateSchemaDraft(arg1, arg2) {
  return window['go']['main']['App']['CreateSchemaDraft'](arg1, arg2);
}

export function CreateShard(arg1) {
  return window['go']['main']['App']['CreateShard'](arg1);
}

export function DeactivateShard(arg1) {
  return window['go']['main']['App']['DeactivateShard'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSchemaDraft(arg1) {
  return window['go']['main']['App']['DeleteSchemaDraft'](arg1);
}

export function DeleteShard(arg1) {
  return window['go']['main']['App']['DeleteShard'](arg1);
}

export function ExecuteProjectSchema(arg1) {
  return window['go']['main']['App']['ExecuteProjectSchema'](arg1);
}

export function ExecuteSQL(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSQL'](arg1, arg2);
}

export function GetFailedShardExecutions(arg1) {
  return window['go']['main']['App']['GetFailedShardExecutions'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSchemaExecutionStatus(arg1) {
  return window['go']['main']['App']['GetSchemaExecutionStatus'](arg1);
}

export function GetSchemaHistory(arg1) {
  return window['go']['main']['App']['GetSchemaHistory'](arg1);
}

export function GetShardConnection(arg1) {
  return window['go']['main']['App']['GetShardConnection'](arg1);
}

export function GetShardKeys(arg1) {
  return window['go']['main']['App']['GetShardKeys'](arg1);
}

export function GetShards(arg1) {
  return window['go']['main']['App']['GetShards'](arg1);
}

export function GetWailsConfig() {
  return window['go']['main']['App']['GetWailsConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RecomputeKeys(arg1) {
  return window['go']['main']['App']['RecomputeKeys'](arg1);
}

export function ReplaceShardKeys(arg1, arg2) {
  return window['go']['main']['App']['ReplaceShardKeys'](arg1, arg2);
}

export function RetrySchemaExecution(arg1) {
  return window['go']['main']['App']['RetrySchemaExecution'](arg1);
}

export function UpdateSchemaDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSchemaDraft'](arg1, arg2, arg3);
}

export function UpdateShardConnection(arg1) {
  return window['go']['main']['App']['UpdateShardConnection'](arg1);
}
