// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {main} from '../models';

export function ActivateProject(arg1:string):Promise<void>;

export function ActivateShard(arg1:string):Promise<void>;

export function ApplyDDL(arg1:string,arg2:string):Promise<void>;

export function CommitSchemaDraft(arg1:string,arg2:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<repository.Project>;

export function CreateSchemaDraft(arg1:string,arg2:string):Promise<repository.ProjectSchema>;

export function CreateShard(arg1:string):Promise<repository.Shard>;

export function DeactivateShard(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSchemaDraft(arg1:string):Promise<void>;

export function DeleteShard(arg1:string):Promise<void>;

export function ExecuteProjectSchema(arg1:string):Promise<void>;

export function ExecuteSQL(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetFailedShardExecutions(arg1:string):Promise<Array<repository.SchemaExecutionStatus>>;

export function GetProjects():Promise<Array<repository.Project>>;

export function GetSchemaExecutionStatus(arg1:string):Promise<Array<repository.SchemaExecutionStatus>>;

export function GetSchemaHistory(arg1:string):Promise<Array<repository.ProjectSchema>>;

export function GetShardConnection(arg1:string):Promise<repository.ShardConnection>;

export function GetShardKeys(arg1:string):Promise<Array<repository.ShardKeys>>;

export function GetShards(arg1:string):Promise<Array<repository.Shard>>;

export function GetWailsConfig():Promise<main.WailsConfig>;

export function Greet(arg1:string):Promise<string>;

export function RecomputeKeys(arg1:string):Promise<void>;

export function ReplaceShardKeys(arg1:string,arg2:Array<repository.ShardKeyRecord>):Promise<void>;

export function RetrySchemaExecution(arg1:string):Promise<void>;

export function UpdateSchemaDraft(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateShardConnection(arg1:repository.ShardConnection):Promise<void>;
